[package]
name = "gvas-viewer-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.223"
gvas = {version = "0.10.0", features = ["serde"]}
egui = "0.32.3"
eframe = "0.32.3"
serde_json = "1.0.145"
rfd = "0.15.4"
gvas2json = "0.1.0"
chrono = { version = "0.4.42"}
